// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Button1;
void ui_event_Label1(lv_event_t * e);
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label4;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label6;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label_th;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_star_png);    // assets/STAR.png
LV_IMG_DECLARE(ui_img_star1_png);    // assets/STAR1.png
LV_IMG_DECLARE(ui_img_logo01_png);    // assets/logo01.png

void update_display_task(void *pvParameters);

LV_FONT_DECLARE(ui_font_stxhei16);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
