// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

#include "freertos/FreeRTOS.h"
#include "freertos/portmacro.h"
#include "freertos/semphr.h"
#include "freertos/timers.h"
#include <assert.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "cJSON.h"
#include "esp_log.h"
#include "esp_system.h"
#include "esp_crc.h"
#include "mqtt.h"


static const char *TAG = "Button1_Callback";
// extern esp_mqtt_client_handle_t client;
const char *global_message = NULL;
// lv_event_t *event1;

// bool mqtt_connected1 = false;
// extern uint8_t target_mac[];

// static const char *TAG = "Panel2";
// static uint8_t target_mac[ESP_NOW_ETH_ALEN] = {0x7C, 0xDF, 0xA1, 0xB8, 0xBE,
// 0xFC};

// int message_counters[NUM_MODES] = {0};
typedef enum
{
  MODE_A1,
  MODE_A2,
  MODE_B1,
  MODE_B2,
  MODE_C1,
  MODE_C2,
  NUM_MODES
} MessageMode;

MessageMode current_modes[NUM_MODES] = {MODE_A1, MODE_B1, MODE_C1};

void button_event_cb(lv_event_t *event, MessageMode mode, int msg1, int msg2)
{
  if (event->code == LV_EVENT_VALUE_CHANGED)
  {
    if (event->code == LV_EVENT_VALUE_CHANGED)
    {
      lv_obj_t *obj = lv_event_get_target(event);
      bool state = lv_obj_get_state(obj) & LV_STATE_CHECKED;
      // global_message = state ? msg1 : msg2;
      // ESP_LOGI(TAG, "global_message_in_button_event: %s", global_message);
      // xTaskCreate(mqtt_publish_task, "mqtt_publish_task", 1024*5, (void*)global_message, 5, NULL);
      char json_message[50]; // 假设JSON消息不会超过50个字符

      if(state) {
        snprintf(json_message, sizeof(json_message), "{\"LED_CTR\": %d}", msg1);
      } else {
        snprintf(json_message, sizeof(json_message), "{\"LED_CTR\": %d}", msg2);
      }

      ESP_LOGI(TAG, "global_message_in_button_event: %s", json_message);
      xTaskCreate(mqtt_publish_task, "mqtt_publish_task", 1024*5, (void*)json_message, 5, NULL);
    
    }
  }
}
void mqtt_publish_task(void *param)
{
    char *message = (char *)param;
    if(mqtt_connected)
    {
        // MQTT已连接，发送消息
        // sprintf(topic, "/sys/openiitagateway01/%s/c/#",  user_id);
        // sprintf(topic, "/openiitagateway01/%s/c/#",  user_id);
        //根据MQTT规范，#和+这两个通配符只能在订阅主题时使用，不能在发布消息时使用
        // int msg_id = esp_mqtt_client_publish(client, topic, message, 0, 0, 0);
        int msg_id = esp_mqtt_client_publish(client, "/iot/2742/de", message, 0, 0, 0);
        ESP_LOGI(TAG, "sent publish successful, msg_id=%d", msg_id);
    }
    else
    {
        // MQTT未连接，不能发送消息
        ESP_LOGE(TAG, "MQTT is not connected, cannot send message");
    }
    vTaskDelete(NULL); // 删除任务
}

static void button4_event_cb(lv_event_t *event)
{
  ESP_LOGI(TAG, "button4");
  button_event_cb(event, MODE_A1, 1, 0);
  // button_event_cb(event);
}

static void button2_event_cb(lv_event_t *event)
{
  ESP_LOGI(TAG, "button2");
  button_event_cb(event, MODE_B1, 1, 0);
}
static void button1_event_cb(lv_event_t *event)
{
  ESP_LOGI(TAG, "button1");
  button_event_cb(event, MODE_C1, 1, 0);
}

void ui_event_comp_Panel2_Button1(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  lv_obj_t **comp_Panel2 = lv_event_get_user_data(e);
  if (event_code == LV_EVENT_CLICKED)
  {
    _ui_checked_set_text_value(comp_Panel2[UI_COMP_PANEL2_BUTTON1_LABEL1],
                               target, "1", "0");
  }
}
void ui_event_comp_Panel2_Button2(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  lv_obj_t **comp_Panel2 = lv_event_get_user_data(e);
  if (event_code == LV_EVENT_CLICKED)
  {
    _ui_checked_set_text_value(comp_Panel2[UI_COMP_PANEL2_BUTTON2_LABEL3],
                               target, "1", "0");
  }
}
void ui_event_comp_Panel2_Button4(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  lv_obj_t **comp_Panel2 = lv_event_get_user_data(e);
  if (event_code == LV_EVENT_CLICKED)
  {
    _ui_checked_set_text_value(comp_Panel2[UI_COMP_PANEL2_BUTTON4_LABEL4],
                               target, "ON", "OFF");
  }
}

void ui_event_comp_Panel2_Arc2(lv_event_t *e) // arc回调函数
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  lv_obj_t **comp_Panel2 = lv_event_get_user_data(e);
  if (event_code == LV_EVENT_VALUE_CHANGED)
  {
    _ui_arc_set_text_value(comp_Panel2[UI_COMP_PANEL2_ARC2_LABEL2], target, "",
                           "%");
  }
}

// COMPONENT Panel2

lv_obj_t *ui_Panel2_create(lv_obj_t *comp_parent)
{

  lv_obj_t *cui_Panel2;
  cui_Panel2 = lv_obj_create(comp_parent);
  lv_obj_set_width(cui_Panel2, 300);
  lv_obj_set_height(cui_Panel2, 230);
  lv_obj_set_align(cui_Panel2, LV_ALIGN_CENTER);
  lv_obj_clear_flag(cui_Panel2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  lv_obj_t *cui_Button1;
  cui_Button1 = lv_btn_create(cui_Panel2);
  lv_obj_set_width(cui_Button1, 100);
  lv_obj_set_height(cui_Button1, 50);
  lv_obj_set_x(cui_Button1, 83);
  lv_obj_set_y(cui_Button1, 70);
  lv_obj_set_align(cui_Button1, LV_ALIGN_CENTER);
  lv_obj_add_flag(cui_Button1, LV_OBJ_FLAG_CHECKABLE |
                                   LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
  lv_obj_clear_flag(cui_Button1, LV_OBJ_FLAG_SCROLLABLE);        /// Flags
  // cui_Button1 = lv_btn_create(cui_Panel2);
  // lv_obj_add_event_cb(cui_Button1, button_event_handler, LV_EVENT_VALUE_CHANGED,NULL);
  lv_obj_add_event_cb(cui_Button1, button1_event_cb, LV_EVENT_VALUE_CHANGED, NULL);

  lv_obj_t *cui_Label1;
  cui_Label1 = lv_label_create(cui_Button1);
  lv_obj_set_width(cui_Label1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(cui_Label1, LV_SIZE_CONTENT); /// 1
  lv_obj_set_align(cui_Label1, LV_ALIGN_CENTER);
  lv_label_set_text(cui_Label1, "OFF1");

  lv_obj_t *cui_Button2;
  cui_Button2 = lv_btn_create(cui_Panel2);
  lv_obj_set_width(cui_Button2, 100);
  lv_obj_set_height(cui_Button2, 50);
  lv_obj_set_x(cui_Button2, 83);
  lv_obj_set_y(cui_Button2, 0);
  lv_obj_set_align(cui_Button2, LV_ALIGN_CENTER);
  lv_obj_add_flag(cui_Button2, LV_OBJ_FLAG_CHECKABLE |
                                   LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
  lv_obj_clear_flag(cui_Button2, LV_OBJ_FLAG_SCROLLABLE);        /// Flags
  lv_obj_add_event_cb(cui_Button2, button2_event_cb, LV_EVENT_VALUE_CHANGED,
                      NULL);

  lv_obj_t *cui_Label3;
  cui_Label3 = lv_label_create(cui_Button2);
  lv_obj_set_width(cui_Label3, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(cui_Label3, LV_SIZE_CONTENT); /// 1
  lv_obj_set_align(cui_Label3, LV_ALIGN_CENTER);
  lv_label_set_text(cui_Label3, "OFF2");

  lv_obj_t *cui_Button4;
  cui_Button4 = lv_btn_create(cui_Panel2);
  lv_obj_set_width(cui_Button4, 100);
  lv_obj_set_height(cui_Button4, 50);
  lv_obj_set_x(cui_Button4, 83);
  lv_obj_set_y(cui_Button4, -71);
  lv_obj_set_align(cui_Button4, LV_ALIGN_CENTER);
  lv_obj_add_flag(cui_Button4, LV_OBJ_FLAG_CHECKABLE |
                                   LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
  lv_obj_clear_flag(cui_Button4, LV_OBJ_FLAG_SCROLLABLE);        /// Flags
  lv_obj_add_event_cb(cui_Button4, button4_event_cb, LV_EVENT_VALUE_CHANGED,
                      NULL);

  lv_obj_t *cui_Label4;
  cui_Label4 = lv_label_create(cui_Button4);
  lv_obj_set_width(cui_Label4, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(cui_Label4, LV_SIZE_CONTENT); /// 1
  lv_obj_set_align(cui_Label4, LV_ALIGN_CENTER);
  lv_label_set_text(cui_Label4, "OFF3");

  lv_obj_t *cui_Arc2;
  cui_Arc2 = lv_arc_create(cui_Panel2);
  lv_obj_set_width(cui_Arc2, 150);
  lv_obj_set_height(cui_Arc2, 150);
  lv_obj_set_x(cui_Arc2, -67);
  lv_obj_set_y(cui_Arc2, 1);
  lv_obj_set_align(cui_Arc2, LV_ALIGN_CENTER);

  lv_obj_t *cui_Label2;
  cui_Label2 = lv_label_create(cui_Arc2);
  lv_obj_set_width(cui_Label2, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(cui_Label2, LV_SIZE_CONTENT); /// 1
  lv_obj_set_align(cui_Label2, LV_ALIGN_CENTER);
  lv_label_set_text(cui_Label2, "50");

  lv_obj_t **children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_PANEL2_NUM);
  children[UI_COMP_PANEL2_PANEL2] = cui_Panel2;
  children[UI_COMP_PANEL2_BUTTON1] = cui_Button1;
  children[UI_COMP_PANEL2_BUTTON1_LABEL1] = cui_Label1;
  children[UI_COMP_PANEL2_BUTTON2] = cui_Button2;
  children[UI_COMP_PANEL2_BUTTON2_LABEL3] = cui_Label3;
  children[UI_COMP_PANEL2_BUTTON4] = cui_Button4;
  children[UI_COMP_PANEL2_BUTTON4_LABEL4] = cui_Label4;
  children[UI_COMP_PANEL2_ARC2] = cui_Arc2;
  children[UI_COMP_PANEL2_ARC2_LABEL2] = cui_Label2;
  lv_obj_add_event_cb(cui_Panel2, get_component_child_event_cb,
                      LV_EVENT_GET_COMP_CHILD, children);
  lv_obj_add_event_cb(cui_Panel2, del_component_child_event_cb, LV_EVENT_DELETE,
                      children);

  lv_obj_add_event_cb(cui_Arc2, ui_event_comp_Panel2_Arc2, LV_EVENT_ALL,
                      children);

  lv_obj_add_event_cb(cui_Button1, ui_event_comp_Panel2_Button1,
                      LV_EVENT_CLICKED, children);
  lv_obj_add_event_cb(cui_Button2, ui_event_comp_Panel2_Button2,
                      LV_EVENT_CLICKED, children);
  lv_obj_add_event_cb(cui_Button4, ui_event_comp_Panel2_Button4, LV_EVENT_ALL,
                      children);

  ui_comp_Panel2_create_hook(cui_Panel2);
  return cui_Panel2;
}
/*
lv_obj_add_event_cb(cui_Panel2, del_component_child_event_cb, LV_EVENT_DELETE,
children); static void del_component_child_event_cb(lv_event_t *e) { lv_obj_t
**children = lv_event_get_user_data(e); lv_mem_free(children);
}
*/