// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "aht20.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, lv_pct(100));
    lv_obj_set_height(ui_Panel1, lv_pct(100));
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_Button1, 50);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 115);
    lv_obj_set_y(ui_Button1, 73);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_border_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_border_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_border_width(ui_Button1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "开灯");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFCFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_stxhei16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_Panel2, 200);
    lv_obj_set_height(ui_Panel2, 180);
    lv_obj_set_x(ui_Panel2, -41);
    lv_obj_set_y(ui_Panel2, -15);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_Image1, &ui_img_star_png);
    lv_obj_set_width(ui_Image1, 50);
    lv_obj_set_height(ui_Image1, 50);
    lv_obj_set_x(ui_Image1, -63);
    lv_obj_set_y(ui_Image1, -54);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Image1, &ui_img_star1_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_Panel2);
    lv_obj_set_width(ui_TextArea1, 70);
    lv_obj_set_height(ui_TextArea1, 20);
    lv_obj_set_x(ui_TextArea1, 40);
    lv_obj_set_y(ui_TextArea1, 75);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "text...");
    lv_obj_set_style_border_color(ui_TextArea1, lv_color_hex(0x8F8F8F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -39);
    lv_obj_set_y(ui_Label5, 59);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "湿度");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_stxhei16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -41);
    lv_obj_set_y(ui_Label2, 3);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "PRESS KEY");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_stxhei16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_t1 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label_t1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_t1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_t1, 100);
    lv_obj_set_y(ui_Label_t1, -40);
    lv_obj_set_align(ui_Label_t1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_t1, "#");
    lv_obj_set_style_text_font(ui_Label_t1, &ui_font_stxhei16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_t2 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label_t2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_t2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_t2, 100);
    lv_obj_set_y(ui_Label_t2, -60);
    lv_obj_set_align(ui_Label_t2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_t2, "#");
    lv_obj_set_style_text_font(ui_Label_t2, &ui_font_stxhei16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_t3 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label_t3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_t3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_t3, 100);
    lv_obj_set_y(ui_Label_t3, -80);
    lv_obj_set_align(ui_Label_t3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_t3, "#");
    lv_obj_set_style_text_font(ui_Label_t3, &ui_font_stxhei16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -41);
    lv_obj_set_y(ui_Label4, 30);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "温度");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_stxhei16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_Button3, 50);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, 116);
    lv_obj_set_y(ui_Button3, -74);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_border_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_border_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_border_width(ui_Button3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "设置");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFCFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label6, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_stxhei16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Label1, ui_event_Label1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}

void update_display_task(void *pvParameters) {

    while (1) {
        // 读取AHT20数据
        float temperature = aht20_data_t.temperature;
        float humidity = aht20_data_t.rel_humidity;
        // ESP_LOGI(TAG, "Temperature: %.2f C, Humidity: %.2f %%", temperature, humidity);

        // 显示数据
        char buf[32];
        char buf1[32];
        snprintf(buf, sizeof(buf), "温度: %.2f ", temperature);
        snprintf(buf1, sizeof(buf1), "湿度: %.2f %%",  humidity);
        lv_label_set_text(ui_Label4, buf);
        lv_label_set_text(ui_Label5, buf1);

        // 等待一段时间
        vTaskDelay(pdMS_TO_TICKS(1000));
    }
}
